### 회원가입

POST  http://localhost:8080/auth/signup
Content-Type: application/json

{
  "name": "testname",
  "email": "admin@admin.com",
  "password": "1234"
}

### 로그인

POST http://localhost:8080/auth/login
Content-Type: application/x-www-form-urlencoded

username=admin@admin.com&password=1234

#{
#  "email": "admin@admin.com",
#  "password": "12345"
#}

### 메인 페이지
GET http://localhost:8080
Cookie: SESSION=ZWQyMmFhNzYtNmZhMi00ZmYxLTlkNjgtY2NhODFhM2IwMzc2