### 로그인

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "12345"
}

### 인증 페이지 요청

GET http://localhost:8080/test
Content-Type: application/json
Authorization: eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxIn0.f7jo5sHBXTeQtBnuNtUZZFqsta3jgkuErbAuFqze87J8kYaNR5sKMsoypYPEetUI