### 회원가입

POST  http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "name": "testname",
  "email": "test@test.com",
  "password": "12345678",
  "phone": "01012345678",
  "birthDt": "1998-09-19",
  "address": {
    "postal": 12345,
    "address": "주소"
  }
}

### 로그인

POST http://localhost:8080/api/auth/login
Content-Type: application/json

//username=admin@admin.com&password=1234
{
  "email": "test@test.com",
  "password": "12345678"
}

### 토큰 재발급
POST http://localhost:8080/api/auth/reissue
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJ1c2VybmFtZSI6InRlc3RAdGVzdC5jb20iLCJpYXQiOjE3Njg0NTQzNjcsImV4cCI6MTc2ODQ1NjE2N30.mAlAavkOVs0-BUfZKNIbu5aZIziLAgosxQnBw2Aryvls9DhcTN9QbbU5FgmwwuJf
Cookie: refreshToken=5cd1130f-ab7c-4b44-a0ae-2d04723c9c5a

### 권한 없는 페이지
GET http://localhost:8080/api/test/permit

### 유저 권한 페이지
GET http://localhost:8080/api/test/auth
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJ1c2VybmFtZSI6InRlc3RAdGVzdC5jb20iLCJpYXQiOjE3Njg0NTI1NTcsImV4cCI6MTc2ODQ1NDM1N30.RM0ewtZqnkwMP-9FeNQaFLy86s1rgmUtvu7ZYdiZ86LpUox-ISETjEiNo3-pJTaa


### 메인 페이지
GET http://localhost:8080
Cookie: SESSION=Mjk1MjRhOTktNWY1Zi00MTRlLTkxODQtMmYxOTBlNTNhOGZh

### 사용자 페이지
GET http://localhost:8080/user
Cookie: SESSION=NjQxMmZiMDYtZTY0Ni00YmQ5LWI0YjEtMjMwODc4Nzk5NzYy

### 관리자 페이지
GET http://localhost:8080/admin
Cookie: SESSION=NjQxMmZiMDYtZTY0Ni00YmQ5LWI0YjEtMjMwODc4Nzk5NzYy