### 게시글 작성

POST http://localhost:8080/posts
Content-Type: application/json
Authorization: 555

{
  "title": "제목입니다.",
  "content": "내용입니다."
}


### 게시글 삭제

DELETE http://localhost:8080/posts/3
Content-Type: application/json


### 게시글 리스트 조회

GET http://localhost:8080/api/boards/1/posts?page=90&size=30
Content-Type: application/json

### 게시글 좋아요 수 조회

GET http://localhost:8080/api/posts/2000/likes
Content-Type: application/json
